services:

  sqlabble:
    build: .
    links:
      - mysql
    encrypted_env_file: secret.env.encrypted
    cached: true

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'sqlabble'
    cached: true
