version: '2'

services:

  sqlabble:
    build: .
    depends_on:
      - mysql
    command: go test -race ./...

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'sqlabble'
