version: '2'

services:

  sqlabble:
    build: .
    depends_on:
      - mysql
    env_file: secret.env
    volumes:
      - ./:/go/src/github.com/sqlabble/sqlabble

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'sqlabble'
